/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * availability.java
 *
 * Created on 21 Oct, 2014, 7:02:37 PM
 */

package hotel_managementsystem;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SHRI
 */
public class availability extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    public Object obj1,obj2,obj3,obj4,obj5,obj6;
    String diffday;
    /** Creates new form availability */
    public availability() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Availability of Rooms and proceed to booking");
        setBounds(new java.awt.Rectangle(350, 150, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel1.setText("Arrival Date:");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel2.setText("Departure Date:");

        JTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTable.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Room Type", "Bed Type", "Cost Per Room"
            }
        ));
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel3.setText("Booking for");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/url - Copy.jpg"))); // NOI18N

        jLabel5.setText("day(s)");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thecambridgehotel_hell - Copy.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Plz Enter the Dates, select room and click on Check Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(31, 31, 31)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static final long ONE_HOUR = 60 * 60 * 1000L;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
java.util.Date dt1,dt2;
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        int rows = model.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                model.removeRow(0);
            }
        }


        try
        {
         Class .forName("java.sql.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        dt1=jDateChooser1.getDate();
        dt2=jDateChooser2.getDate();
        String strdtver1=(String) sdf.format(jDateChooser1.getDate());
        String strdtver2=(String) sdf.format(jDateChooser2.getDate());
        long diff=((dt2.getTime()-dt1.getTime()+ONE_HOUR)/(ONE_HOUR*24));
        diffday=Long.toString(diff);
        if(diff<=0){
        JOptionPane.showMessageDialog(rootPane, "Error: Date. Please check the dates.");
        }
        else{
        jTextField1.setText(diffday);
        String sql="SELECT room_no, room_type, room_bed, room_rate FROM roomdetail "
                + "where room_no NOT IN (SELECT room_no FROM bookingtable WHERE DATE(date_to) >= '"
                + strdtver1 + "' AND DATE(date_fro) <= '" + strdtver2 + "');";
         stmt = con.createStatement();
         rs = stmt.executeQuery(sql);

        while (rs.next()) {
                String rn = rs.getString("room_no");
                String rt = rs.getString("room_type");
                String bt = rs.getString("room_bed");
                String cpr = rs.getString("room_rate");
                model.addRow(new Object[] {rn, rt, bt, cpr});
            }}
        }
        catch(Exception e)
        {
         System.out.println(e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rno=JTable.getSelectedRow();
        obj1 = JTable.getValueAt(rno, 0);
        obj2 = JTable.getValueAt(rno, 1);
        obj3 = JTable.getValueAt(rno, 2);
        obj4 = JTable.getValueAt(rno, 3);
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String dt1=(String) sdf.format(jDateChooser1.getDate());
        String dt2=(String) sdf.format(jDateChooser2.getDate());
        String nd=jTextField1.getText();
        try
        {
         Class .forName("java.sql.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
        String sql="SELECT *from temp";
         stmt = con.createStatement();
         rs = stmt.executeQuery(sql);
        while (rs.next()) {}
         String del="delete from temp";
         int rowsdel=stmt.executeUpdate(del);
String query="insert into temp values('"+obj1+"','"+obj2+"','"+obj3+"','"+obj4+"','"+dt1+"','"+dt2+"','"+nd+"')";
int rowseff=stmt.executeUpdate(query);        
        }
        catch(Exception e)
        {
         System.out.println(e.getMessage());
        }
        bookroom br=new bookroom();
                br.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public Object GetData(JTable jTable1, int row_index, int col_index){
		return jTable1.getModel().getValueAt(row_index, col_index);
	}

    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked

        int rno=JTable.getSelectedRow();
        Object obj0=JTable.getValueAt(rno, 3);
        obj1 = JTable.getValueAt(rno, 0);
        obj2 = JTable.getValueAt(rno, 1);
        obj3 = JTable.getValueAt(rno, 2);
        obj4 = JTable.getValueAt(rno, 3);
                SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String dt1=(String) sdf.format(jDateChooser1.getDate());
        String dt2=(String) sdf.format(jDateChooser2.getDate());
        // TODO add your handling code here:
    }//GEN-LAST:event_JTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
