/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * customermanag.java
 *
 * Created on 21 Oct, 2014, 7:03:18 PM
 */

package hotel_managementsystem;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author SHRI
 */
public class customermanag extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    /** Creates new form customermanag */
    public customermanag() {
        initComponents();
    }
    public void disrecors(){
    try
        {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String bkid=cno.getText();
            String sql = "SELECT * FROM bookingtable where book_id='"+bkid+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            while (rs.next()){
            rno.setText(rs.getString("room_no"));
            arr.setText(rs.getString("date_fro"));
            dep.setText(rs.getString("date_to"));
}}
catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }}
    public void displayRecord(){
        try
        {
            String bkid=rs.getString("book_id");
            cno.setText(rs.getString("book_id"));
            vname.setText(rs.getString("cust_name"));
            vadd.setText(rs.getString("cust_add"));
            vcity.setText(rs.getString("cust_city"));
            vstate.setText(rs.getString("cust_state"));
            vcountry.setText(rs.getString("cust_country"));
            vphone.setText(rs.getString("cust_ph"));
            vidproof.setText(rs.getString("cust_proof"));
            vidpfno.setText(rs.getString("cust_id_no"));
            vmars.setText(rs.getString("cust_mar_stat"));
            vnationality.setText(rs.getString("cust_nation"));
            noofadult.setText(rs.getString("cust_adult"));
            noofchild.setText(rs.getString("cust_child"));
            purofvisit.setText(rs.getString("cust_purpos"));
            bid.setText(rs.getString("book_id"));
            bamt.setText(rs.getString("cust_bill"));
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");

        }
        catch(Exception ec)
        {}
        BufferedImage bi1;
            try {
                String imgn=(rs.getString("imgadd")).replace("|", "\\");
                bi1 = ImageIO.read(new File(imgn));
                ImageIcon icon1 = new ImageIcon(bi1);
                Image img = icon1.getImage();
                ImageIcon icon = new ImageIcon(imgn);
                Image scaleImage = icon.getImage().getScaledInstance(125, 144, Image.SCALE_DEFAULT);
                jLabel30.setIcon(new ImageIcon(scaleImage));
            } catch (Exception e) {
                System.out.println(e);
            }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        vadd = new javax.swing.JTextField();
        vcity = new javax.swing.JTextField();
        vstate = new javax.swing.JTextField();
        vcountry = new javax.swing.JTextField();
        vphone = new javax.swing.JTextField();
        vidproof = new javax.swing.JTextField();
        vidpfno = new javax.swing.JTextField();
        vmars = new javax.swing.JTextField();
        vnationality = new javax.swing.JTextField();
        noofadult = new javax.swing.JTextField();
        noofchild = new javax.swing.JTextField();
        purofvisit = new javax.swing.JTextField();
        bid = new javax.swing.JTextField();
        bamt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        arr = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        searchnamecmd = new javax.swing.JButton();
        firstcmd = new javax.swing.JButton();
        lastcmd = new javax.swing.JButton();
        searchidcmd = new javax.swing.JButton();
        nextcmd1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rno = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cno = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Management Form");
        setBounds(new java.awt.Rectangle(310, 90, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Visitor Management Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultpic.png"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Visitor Name");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Visitor Address");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Visitor City");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Visitor State");

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Visitor Country");

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Visitor Phone");

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Visitor ID Proof");

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Visitor ID Proof Number");

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Visitor Marital Status");

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("No. of Adult(s) with visitor");

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("No. of Child(ren) with visitor");

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Visitor Nationality");

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Purpose of visit");

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Bill Amount");

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Booking ID");

        vname.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vadd.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vcity.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vstate.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vcountry.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vphone.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vidproof.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vidpfno.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vmars.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        vnationality.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        noofadult.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        noofchild.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        purofvisit.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        bid.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        bamt.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Arrival");

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Departure");

        arr.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        dep.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));

        searchnamecmd.setBackground(new java.awt.Color(204, 255, 153));
        searchnamecmd.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        searchnamecmd.setForeground(new java.awt.Color(204, 0, 0));
        searchnamecmd.setText("Click Here to Search by Name");
        searchnamecmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnamecmdActionPerformed(evt);
            }
        });

        firstcmd.setBackground(new java.awt.Color(204, 255, 153));
        firstcmd.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        firstcmd.setForeground(new java.awt.Color(204, 0, 0));
        firstcmd.setText("First");
        firstcmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstcmdActionPerformed(evt);
            }
        });

        lastcmd.setBackground(new java.awt.Color(204, 255, 153));
        lastcmd.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        lastcmd.setForeground(new java.awt.Color(204, 0, 0));
        lastcmd.setText("Last");
        lastcmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastcmdActionPerformed(evt);
            }
        });

        searchidcmd.setBackground(new java.awt.Color(204, 255, 153));
        searchidcmd.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        searchidcmd.setForeground(new java.awt.Color(204, 0, 0));
        searchidcmd.setText("Click Here to Search By Book. ID");
        searchidcmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchidcmdActionPerformed(evt);
            }
        });

        nextcmd1.setBackground(new java.awt.Color(204, 255, 153));
        nextcmd1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        nextcmd1.setForeground(new java.awt.Color(204, 0, 0));
        nextcmd1.setText("Close");
        nextcmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextcmd1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14));
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bamt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noofadult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vnationality, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noofchild, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vname)
                    .addComponent(vadd)
                    .addComponent(vcity)
                    .addComponent(vstate)
                    .addComponent(vcountry)
                    .addComponent(vphone)
                    .addComponent(vidproof)
                    .addComponent(vidpfno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vmars, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel17)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel18)))
                            .addContainerGap(20, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchnamecmd)
                                    .addComponent(searchidcmd))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nextcmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstcmd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastcmd, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                            .addGap(30, 30, 30)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {searchidcmd, searchnamecmd});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(vstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(vcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(vphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(vidproof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(vidpfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(vmars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(vnationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(noofadult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(noofchild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(purofvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(bamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(searchnamecmd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchidcmd)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastcmd)
                            .addComponent(firstcmd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextcmd1)
                            .addComponent(jButton2))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        rno.setFont(new java.awt.Font("Tahoma", 1, 12));
        rno.setText("00000");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel28.setText("Room No.");

        cno.setFont(new java.awt.Font("Tahoma", 1, 12));
        cno.setText("00000");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setText("Booking ID.");

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel1.setText("Customer Management Form");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/url - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel29)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cno))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rno, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cno, rno});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastcmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastcmdActionPerformed
try
        {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM custdetail";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.last();
            displayRecord();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        disrecors();
}//GEN-LAST:event_lastcmdActionPerformed

    private void firstcmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstcmdActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM custdetail";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        disrecors();
    }//GEN-LAST:event_firstcmdActionPerformed

    private void searchnamecmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnamecmdActionPerformed
String name=JOptionPane.showInputDialog(null,"Search By Name","Enter Name to Search");
try
        {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM custdetail where cust_name like '"+name+"%'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        disrecors();
// TODO add your handling code here:
    }//GEN-LAST:event_searchnamecmdActionPerformed

    private void searchidcmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidcmdActionPerformed
String name=JOptionPane.showInputDialog(null,"Search By Booking ID","Enter book id to Search");
try
        {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM custdetail where book_id='"+name+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        disrecors();        // TODO add your handling code here:
    }//GEN-LAST:event_searchidcmdActionPerformed

    private void nextcmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextcmd1ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_nextcmd1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            cno.setText("00000");
            vname.setText("");
            vadd.setText("");
            vcity.setText("");
            vstate.setText("");
            vcountry.setText("");
            vphone.setText("");
            vidproof.setText("");
            vidpfno.setText("");
            vmars.setText("");
            vnationality.setText("");
            noofadult.setText("");
            noofchild.setText("");
            purofvisit.setText("");
            bid.setText("");
            bamt.setText("");
            rno.setText("00000");
            arr.setText("");
            dep.setText("");
            jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultpic.png")));// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customermanag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arr;
    private javax.swing.JTextField bamt;
    private javax.swing.JTextField bid;
    private javax.swing.JLabel cno;
    private javax.swing.JTextField dep;
    private javax.swing.JButton firstcmd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lastcmd;
    private javax.swing.JButton nextcmd1;
    private javax.swing.JTextField noofadult;
    private javax.swing.JTextField noofchild;
    private javax.swing.JTextField purofvisit;
    private javax.swing.JLabel rno;
    private javax.swing.JButton searchidcmd;
    private javax.swing.JButton searchnamecmd;
    private javax.swing.JTextField vadd;
    private javax.swing.JTextField vcity;
    private javax.swing.JTextField vcountry;
    private javax.swing.JTextField vidpfno;
    private javax.swing.JTextField vidproof;
    private javax.swing.JTextField vmars;
    private javax.swing.JTextField vname;
    private javax.swing.JTextField vnationality;
    private javax.swing.JTextField vphone;
    private javax.swing.JTextField vstate;
    // End of variables declaration//GEN-END:variables

}
