/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on 23 Oct, 2014, 3:25:28 PM
 */

package hotel_managementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author SHRI
 */
public class login extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        mtype = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to Hotel Management System");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(450, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(462, 386));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chdoor.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 170, 150, 160);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 190, 70, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 230, 61, 15);

        uid.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(uid);
        uid.setBounds(180, 210, 120, 21);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 280, 120, 20);

        mtype.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        mtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Recepient" }));
        getContentPane().add(mtype);
        mtype.setBounds(200, 170, 90, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButton3.setText("Register New User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 300, 130, 21);
        getContentPane().add(pwd);
        pwd.setBounds(180, 250, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chbg.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
pwd.setVisible(false);
uid.setVisible(false);
jLabel1.setVisible(false);
jLabel2.setVisible(false);
jButton2.setVisible(false);
mtype.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
pwd.setVisible(true);
uid.setVisible(true);
jLabel1.setVisible(true);
jLabel2.setVisible(true);
jButton2.setVisible(true);
mtype.setVisible(true);
jButton1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","tiger");
            String member=(String)mtype.getSelectedItem();
            String sql = "select * from user where uid='"+uid.getText()+"' and mtype='"+member+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){
            String password=rs.getString("pwd");
            String memtype=rs.getString("mtype");
            String entpwd=pwd.getText();
            
            if (password.equals(entpwd) && memtype.equals(member)){
                if(member=="Manager"){
                new mainmenu().setVisible(true);
                this.setVisible(false);}
                else{new mainmenur().setVisible(true);
                this.setVisible(false);}
                JOptionPane.showMessageDialog(rootPane, rs.getString("uid")+", Welcome to Cambridge Hotel.");
            }else{JOptionPane.showMessageDialog(null, "Please try again");}}
            else{JOptionPane.showMessageDialog(null, "Please try again");}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new register().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox mtype;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables

}
