/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * staffmng.java
 *
 * Created on 23 Oct, 2014, 1:18:11 PM
 */

package hotel_managementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author SHRI
 */
public class staffmng extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    String name,address,city,state,country,cno,spost,salary;
    int id;
    /** Creates new form staffmng */
    public staffmng() {
        initComponents();
    }

    public void displayRecord(){
        try
        {
            sid.setText(rs.getString("id"));
            lsid.setText(rs.getString("id"));
            sname.setText(rs.getString("name"));
            sadd.setText(rs.getString("address"));
            scity.setText(rs.getString("city"));
            sstate.setText(rs.getString("state"));
            scountry.setText(rs.getString("country"));
            scno.setText(rs.getString("cno"));
            post.setSelectedItem(rs.getString("post"));
            sal.setText(rs.getString("salary"));
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
        }
    catch(Exception ec)
        {}
    }
        public void fetchFromTextF(){

            id=Integer.parseInt(sid.getText());
            name=sname.getText();
            address=sadd.getText();
            city=scity.getText();
            state=sstate.getText();
            country=scountry.getText();
            cno=scno.getText();
            spost=(String)post.getSelectedItem();
            salary=sal.getText();
    }

    public void clearTextF(){
            sid.setText("");
            lsid.setText("00");
            sname.setText("");
            sadd.setText("");
            scity.setText("");
            sstate.setText("");
            scountry.setText("");
            scno.setText("");
            post.setSelectedItem(null);
            sal.setText("");}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        sadd = new javax.swing.JTextField();
        scity = new javax.swing.JTextField();
        sstate = new javax.swing.JTextField();
        scountry = new javax.swing.JTextField();
        scno = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        searchnamecmd2 = new javax.swing.JButton();
        firstcmd2 = new javax.swing.JButton();
        lastcmd2 = new javax.swing.JButton();
        searchidcmd2 = new javax.swing.JButton();
        sid = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        post = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        upd = new javax.swing.JButton();
        del = new javax.swing.JButton();
        savecmd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lsid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Management Form");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Staff Management Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel18.setText("Name");

        jLabel19.setText("Address");

        jLabel20.setText("City");

        jLabel21.setText("State");

        jLabel22.setText("Country");

        jLabel23.setText("Contact No.");

        jLabel24.setText("Post:");

        jLabel25.setText("Salary");

        searchnamecmd2.setText("Click Here to Search by Name");
        searchnamecmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnamecmd2ActionPerformed(evt);
            }
        });

        firstcmd2.setText("First");
        firstcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstcmd2ActionPerformed(evt);
            }
        });

        lastcmd2.setText("Last");
        lastcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastcmd2ActionPerformed(evt);
            }
        });

        searchidcmd2.setText("Click Here to Search By Book. ID");
        searchidcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchidcmd2ActionPerformed(evt);
            }
        });

        jLabel26.setText("ID");

        post.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Supervisor", "Recepient", "Cook", "Waiter", "Guard" }));

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        upd.setText("Update");
        upd.setEnabled(false);
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.setEnabled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        savecmd.setText("Save");
        savecmd.setEnabled(false);
        savecmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savecmdActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(sadd, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(scity, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(sstate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(scountry, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(scno, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upd)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(del)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addComponent(savecmd))))
                    .addComponent(searchnamecmd2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(searchidcmd2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(firstcmd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(lastcmd2)))
                .addGap(30, 30, 30))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {del, firstcmd2, jButton1, jButton2, jButton3, lastcmd2, savecmd, upd});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(sadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(sstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(scountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(scno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchnamecmd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchidcmd2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstcmd2)
                            .addComponent(lastcmd2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(upd))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(savecmd)
                                .addGap(18, 18, 18)
                                .addComponent(del)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setText("Staff ID.");

        lsid.setFont(new java.awt.Font("Tahoma", 1, 12));
        lsid.setText("0000");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Staff Management Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lsid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(lsid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchnamecmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnamecmd2ActionPerformed
        String oname=JOptionPane.showInputDialog(null,"Search By Name","Enter Name to Search");
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM staff where name like '"+oname+"%'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        upd.setEnabled(true);
        del.setEnabled(true);
        // TODO add your handling code here:
}//GEN-LAST:event_searchnamecmd2ActionPerformed

    private void firstcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstcmd2ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM staff";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
}//GEN-LAST:event_firstcmd2ActionPerformed

    private void lastcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastcmd2ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM staff";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.last();
            displayRecord();
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
}//GEN-LAST:event_lastcmd2ActionPerformed

    private void searchidcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidcmd2ActionPerformed
        String staffid=JOptionPane.showInputDialog(null,"Search By Booking ID","Enter book id to Search");
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM staff where id='"+staffid+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        upd.setEnabled(true);
        del.setEnabled(true);
                // TODO add your handling code here:
}//GEN-LAST:event_searchidcmd2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            clearTextF();
            savecmd.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void savecmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savecmdActionPerformed
try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String sql = "SELECT * FROM staff";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){}
            fetchFromTextF();
                int code = JOptionPane.showConfirmDialog(this, "New member: " + name + " will be created", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (code == JOptionPane.YES_OPTION) {
                    String updatequery = "insert into staff values('"+id+"','"+name+"','"+address+"','"+city+"','"+state+"','"+country+"','"+cno+"','"+spost+"','"+salary+"')";
                    stmt = con.createStatement();
                    int success = stmt.executeUpdate(updatequery);
                        JOptionPane.showMessageDialog(this, "Record Inserted");
                } 
            else{
            JOptionPane.showMessageDialog(rootPane, "Already Exists. Check Details.");}
        } catch (Exception ex) {
JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
savecmd.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_savecmdActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String sql = "SELECT * FROM staff";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){}
            int did=Integer.parseInt(sid.getText());
                int code = JOptionPane.showConfirmDialog(this, "Member: " + did + " will be deleted from database.", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (code == JOptionPane.YES_OPTION) {
                    String updatequery = "DELETE from staff where id='" +did+ "'";
                    stmt = con.createStatement();
                    int success = stmt.executeUpdate(updatequery);
                        JOptionPane.showMessageDialog(this, "Record Deleted");
                        clearTextF();
                } else {JOptionPane.showMessageDialog(this, "Problem in deletion. Retry");
                }
        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String sql = "SELECT * FROM staff";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){
            fetchFromTextF();
                int code = JOptionPane.showConfirmDialog(this, "Member: " + id + " will be updated", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (code == JOptionPane.YES_OPTION) {
                    String updatequery = "update staff set name='"+name+"', address='"+address+"', city='"+city+"', state='"+state+"', country='"+country+"', cno='"+cno+"', post='"+spost+"', salary='"+salary+"' where id='"+id+"'";
                    stmt = con.createStatement();
                    int success = stmt.executeUpdate(updatequery);
                        JOptionPane.showMessageDialog(this, "Updated Successfully");
                } else {JOptionPane.showMessageDialog(this, "Check details...");
                }}
            else{
            JOptionPane.showMessageDialog(rootPane, "Some Problem. Check Details.");}
        } catch (Exception ex) {
JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
upd.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_updActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearTextF();        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffmng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JButton firstcmd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lastcmd2;
    private javax.swing.JLabel lsid;
    private javax.swing.JComboBox post;
    private javax.swing.JTextField sadd;
    private javax.swing.JTextField sal;
    private javax.swing.JButton savecmd;
    private javax.swing.JTextField scity;
    private javax.swing.JTextField scno;
    private javax.swing.JTextField scountry;
    private javax.swing.JButton searchidcmd2;
    private javax.swing.JButton searchnamecmd2;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField sstate;
    private javax.swing.JButton upd;
    // End of variables declaration//GEN-END:variables

}
