/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * staffmng.java
 *
 * Created on 23 Oct, 2014, 1:18:11 PM
 */

package hotel_managementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author SHRI
 */
public class usermanag extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    String name,userid,cno,mtype;
    /** Creates new form staffmng */
    public usermanag() {
        initComponents();
    }

    public void displayRecord(){
        try
        {
            uid.setText(rs.getString("uid"));
            luid.setText(rs.getString("uid"));
            uname.setText(rs.getString("name"));
            ucno.setText(rs.getString("cno"));
            type.setSelectedItem(rs.getString("mtype"));
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
        }
    catch(Exception ec)
        {}
    }
        public void fetchFromTextF(){

            userid=uid.getText();
            name=uname.getText();
            cno=ucno.getText();
            mtype=(String)type.getSelectedItem();
    }

    public void clearTextF(){
            uid.setText("");
            luid.setText("00");
            uname.setText("");
            ucno.setText("");
            type.setSelectedItem(null);}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        ucno = new javax.swing.JTextField();
        searchnamecmd2 = new javax.swing.JButton();
        firstcmd2 = new javax.swing.JButton();
        lastcmd2 = new javax.swing.JButton();
        searchidcmd2 = new javax.swing.JButton();
        uid = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        upd = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        luid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Management");
        setBounds(new java.awt.Rectangle(400, 250, 0, 0));
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "User Management Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel18.setText("Name");

        jLabel23.setText("Contact No.");

        jLabel24.setText("User Type");

        searchnamecmd2.setText("Click Here to Search by Name");
        searchnamecmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnamecmd2ActionPerformed(evt);
            }
        });

        firstcmd2.setText("First");
        firstcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstcmd2ActionPerformed(evt);
            }
        });

        lastcmd2.setText("Last");
        lastcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastcmd2ActionPerformed(evt);
            }
        });

        searchidcmd2.setText("Click Here to Search By User ID");
        searchidcmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchidcmd2ActionPerformed(evt);
            }
        });

        jLabel26.setText("User Id");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Recepient" }));

        upd.setText("Update");
        upd.setEnabled(false);
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.setEnabled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(53, 53, 53)
                        .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(uname, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addComponent(ucno, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchnamecmd2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(searchidcmd2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(upd)
                            .addComponent(firstcmd2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lastcmd2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(del)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(26, 26, 26))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {del, firstcmd2, lastcmd2, upd});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchnamecmd2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(ucno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstcmd2)
                            .addComponent(del)
                            .addComponent(jButton4)))
                    .addComponent(searchidcmd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastcmd2)
                        .addComponent(upd)
                        .addComponent(jButton1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setText("User ID.");

        luid.setFont(new java.awt.Font("Tahoma", 1, 12));
        luid.setText("0000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(luid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(luid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchnamecmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnamecmd2ActionPerformed
        String oname=JOptionPane.showInputDialog(null,"Search By Name","Enter Name to Search");
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM user where name like '"+oname+"%'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        upd.setEnabled(true);
        del.setEnabled(true);
        // TODO add your handling code here:
}//GEN-LAST:event_searchnamecmd2ActionPerformed

    private void firstcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstcmd2ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM user";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
}//GEN-LAST:event_firstcmd2ActionPerformed

    private void lastcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastcmd2ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM user";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.last();
            displayRecord();
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
}//GEN-LAST:event_lastcmd2ActionPerformed

    private void searchidcmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidcmd2ActionPerformed
        String userid=JOptionPane.showInputDialog(null,"Search By Booking ID","Enter book id to Search");
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String query = "SELECT * FROM user where uid like '"+userid+"%'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            rs.first();
            displayRecord();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        upd.setEnabled(true);
        del.setEnabled(true);
                // TODO add your handling code here:
}//GEN-LAST:event_searchidcmd2ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String sql = "SELECT * FROM user";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){}
            String usid=uid.getText();
                int code = JOptionPane.showConfirmDialog(this, "User: " + usid + " will be deleted from database.", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (code == JOptionPane.YES_OPTION) {
                    String updatequery = "DELETE from user where uid='" +usid+ "'";
                    stmt = con.createStatement();
                    int success = stmt.executeUpdate(updatequery);
                        JOptionPane.showMessageDialog(this, "Record Deleted");
                        clearTextF();
                } else {JOptionPane.showMessageDialog(this, "Problem in deletion. Retry");
                }
        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","tiger");
            String sql = "SELECT * FROM user";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){
            fetchFromTextF();
                int code = JOptionPane.showConfirmDialog(this, "User: " + userid + " will be updated", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (code == JOptionPane.YES_OPTION) {
                    String updatequery = "update user set name='"+name+"', cno='"+cno+"', mtype='"+mtype+"' where uid='"+userid+"'";
                    stmt = con.createStatement();
                    int success = stmt.executeUpdate(updatequery);
                        JOptionPane.showMessageDialog(this, "Updated Successfully");
                } else {JOptionPane.showMessageDialog(this, "Check details...");
                }}
            else{
            JOptionPane.showMessageDialog(rootPane, "Some Problem. Check Details.");}
        } catch (Exception ex) {
JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
upd.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_updActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearTextF();        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usermanag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JButton firstcmd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lastcmd2;
    private javax.swing.JLabel luid;
    private javax.swing.JButton searchidcmd2;
    private javax.swing.JButton searchnamecmd2;
    private javax.swing.JComboBox type;
    private javax.swing.JTextField ucno;
    private javax.swing.JTextField uid;
    private javax.swing.JTextField uname;
    private javax.swing.JButton upd;
    // End of variables declaration//GEN-END:variables

}
